# Generated by Django 4.1 on 2024-01-28 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeproduct',
            unique_together={('recipe', 'product')},
        ),
    ]
